import Head from "next/head";
import SiteLayout from "components/Layouts/SiteLayout";
import { Link } from "@mui/material";

export default function Home() {
  return (
    <SiteLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        صفحه <Link href="/profile/settings">تنظیمات کاریری</Link>
      </main>
    </SiteLayout>
  );
}
